version: 0.2

env:
  variables:
    REPO_NAME: "large-test-image"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - ECR_REGISTRY="359181413314.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - aws ecr create-repository --repository-name ${REPO_NAME} --region ${AWS_DEFAULT_REGION} 2>/dev/null || true
  build:
    commands:
      - echo Build started on `date`
      - echo "Building large test image..."
      - docker build -t ${REPO_NAME}:${IMAGE_TAG} .
      - echo "Tagging for ECR..."
      - docker tag ${REPO_NAME}:${IMAGE_TAG} ${ECR_REGISTRY}/${REPO_NAME}:${IMAGE_TAG}
      - echo "Pushing to ECR..."
      - docker push ${ECR_REGISTRY}/${REPO_NAME}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Image size:"
      - docker images ${REPO_NAME}:${IMAGE_TAG} --format 'table {{.Repository}}\t{{.Tag}}\t{{.Size}}'
