version: 0.2

phases:
  pre_build:
    commands:
      - echo checking versions...
      - aws --version
      - docker --version
      - chmod +x build.sh
  build:
    commands:
      - echo Build started on `date`
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`
